from typing import Tuple

import numpy as np


class Skin:
    """
    Skins affects how shapes are rendered by acting on the segments and faces during the
    compilation processes thanks to a dedicated hook. Sub-class must implement the apply()
    member. This base class has no effect on shapes.
    """

    # noinspection PyUnusedLocal,PyMethodMayBeStatic
    def apply(
        self, segments: np.ndarray, faces: np.ndarray, camera_matrix: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        This function is called by the shape once it has generated its segments and faces in
        camera space. The skin may affect any or all of it.
        :param segments: Nx2x3 array of segments generated by the shape
        :param faces: Mx3x3 array of faces generated by the shape
        :param camera_matrix: 4x4 camera projection matrix
        :return: tuple of (segments, faces)
        """

        # do nothing
        return segments, faces
